development:
  adapter: postgresql
  encoding: unicode
  database: bangarang_development
  pool: 5
  username: nickrhys
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bangarang_test
  pool: 5
  username: nickrhys
  password:
